name: news_bloc_clean_architecture
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.18.6
  get_it: ^7.6.0
  intl: ^0.18.1
  retrofit: ^4.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.1
  floor_generator: ^1.2.0
  build_runner: ^2.1.2


  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.otf
        - asset: assets/fonts/muli/Muli-Bold.otf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.otf
          weight: 300
